config/routes.rb
Streamaweb::Application.routes.draw do
 

  resources :target_objects

  resources :profiles

  resources :activities do
#    resources :comments
  end

  resources :verbs, :only => :index
  resources :actors, :only => :index
  resources :objects, :only => :index

  devise_for :users
  devise_for :admin

  resources :network_updates

  root :to => "home#index" 

  #devise_for :users
  resources :users, :only => :show

  devise_scope :user do                                                                                                                                   
    match "/signup" => "devise/registrations#new", :as => :signup
    match "/signin" => "devise/sessions#new", :as => :signin
  end
  match 'home' => 'home#index', as: :user_root 
  match 'my_activities' => 'activities#published', as: :published_activities
  match 'about' => 'home#about', as: :about

  namespace "api" do
    namespace "v1" do
      match 'activities.json' => "activities#index", :action => 'index', :format => 'json', :as => :api_activities
      resources :activities
      resources :comments
    end
  end
  match 'json_stream' => 'home#json_stream', as: :json_stream 

  namespace "admin" do
    resources :activities
  end
  match "admin/activities" => "admin/activities#index", as: :admin_root
end

app/models/activity.rb
class Activity
  include Streama::Activity
  
  activity :new_photo do
    actor :user, :cache => [:first_name]
    object :photo, :cache => [:file]
    target_object :album, :cache => [:title]
  end
  
  activity :new_photo_without_cache do
    actor :user
    object :photo
    target_object :album
  end
  
  activity :comment do
    actor :user, :cache => [:first_name]
    object :comment, :cache => [:content, :inReplyTo]
  end

  activity :post do
    actor :user, :cache => [:first_name]
    object :network_update, :cache => [:content] # note according to: http://activitystrea.ms/head/activity-schema.html#note
    # target_object :newsfeed
  end

  activity :follow do
    actor :user, :cache => [:first_name]
    object :user, :cache => [:first_name]
    # target_object :newsfeed
  end

  has_many :comments

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_filter :authenticate_user!

  def published
    @activities = current_user.published_activities.to_ary
    render :json => @activities.to_json
  end

end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < ApplicationController

  before_filter :authenticate_admin!

  def index
    @activities = Activity.all
  end

  def destroy
    activity = Activity.find(params[:id])
    activity.delete
    redirect_to admin_activities_path 
  end

end

app/controllers/api/v1/activities_controller.rb
class Api::V1::ActivitiesController < ApplicationController

  respond_to :json

  def index
    @activities = Activity.all.to_ary

    respond_with(@activities.to_json)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/activities_helper.rb
module Admin::ActivitiesHelper
end

app/helpers/api/v1/activities_helper.rb
module Api::V1::ActivitiesHelper
end

app/views/activities/_activity.html.erb
<% first_name = activity.actor['first_name'] %>

<li class="well activity-well span8">
  <%= link_to first_name, profile_path(:id => CGI.escape(first_name)) %>
  <%= activity.verb %>
  <%= activity.object['content'] %>    
(at: <%= activity.created_at.strftime("%H:%M %d/%m/%Y")%>)</br>
<%= "Target object: #{activity.target_object}" unless activity.target_object.nil? %>
<div class="actions">
<%= link_to "Comment", "#", :id => "comment-activity-#{activity.id}", :class => "comment" %> | <%= link_to "Like", "#" %>
</div>
</li>

app/views/activities/index.html.erb
<h1>Activities#index</h1>
<p>Find me in app/views/activities/index.html.erb</p>

app/views/activities/published.html.erb
<div class="container">
  <ul>
    <%= @activities.render(self) %>
  </ul>
</div>